### ISSUE TITLE
How to run script

### ISSUE THREAD

**Issue by Nohicom** [reteo/Sprocket#15]
Hello!  This may seem silly, but I need some help.

I can't figure out how to run the sprocket.py script. I have installed Python but don't have any experience with it, and don't know how to use your script to convert the .ini file I wrote into a .xml file for COG.

Thanks in advance!

**Comment by reteo** [comment]
Unfortunately, I haven't been keeping it up for years.  You might want to check out [lawremi's copy](https://github.com/lawremi/Sprocket), which is more up-to-date than this one, and is more likely to work, not only in general, but also with versions of Minecraft newer than 1.7.10.

In both cases, the instructions for using it are in the main page, including the command you need to use to launch it.  Keep in mind that this script was made using version 2 of Python, rather than the current version (3), so you will need to make sure you have that version of Python installed for the script to work.

I hope this helps!

**Comment by Nohicom** [comment]
Alright, thank you!

It was probably the python version discrepancy that was the issue, but I actually found out I don't need COG at all because TFC:TNG (the mod I was trying to create custom ore spawns for) lets you do that stuff natively if you enable it in the config.

Thank you for your help anyway though! If I need this script again in the future I'll try running it with python 2, and hopefully that'll work better.
