### ISSUE TITLE
Cannot inherit settings ('PresetStratum' is not a loaded distribution)

### ISSUE THREAD

**Issue by SvEgiiVEteR** [reteo/Sprocket#3]
Mar 16, 2016
https://gist.github.com/2fcb6d2b24c2bdf9536bf3d422706044

**Comment by SvEgiiVEteR** [comment]
found how to fix)
https://github.com/lawremi/CustomOreGen/blob/master/src/main/resources/config/CustomOreGen_Config_Default.xml
but there are two problems
Fossils&Archaeology.ini
Thaumcraft4.ini
https://gist.github.com/22b0b0d1165522569692b46ab1b396d5
because of these lines:
Prefer Biome Types: Hot, Sandy, Nether, Mesa
configuration is not created.
than replace them? What would have happened as you have in FossilsandArchaeology.xml and Thaumcraft4.xml

**Comment by reteo** [comment]
Yes, where the strata distribution is concerned, Sprocket is currently designed with the next version of Custom Ore Generation in mind.  However, the error was a mistake on my part.  Try it now; it should be fixed.

**Comment by SvEgiiVEteR** [comment]
and 
ThermalFoundation.ini
small errors.
[Ferrous] --- [Nickel]
[Shiny] --- [Platinum]
and missing  ThermalFoundation:Ore:6
[Mithril]

I still made these. 
z_BigReactors.ini
z_bluepower.ini
z_minefantasy2.ini - not ready
z_SGCraft.ini
I can put you to check and if that added them.

**Comment by reteo** [comment]
"Ferrous" and "Shiny" are the official names of the ores.  Yes, they're nickel and platinum, but anyone looking over that configuration without knowing that would be confused, so I left the names as their official versions.

Mithril, or more specifically, "Mana-Infused Ore," doesn't spawn in the world using the normal oregen process.  As such, it was left out of the COG configuration, so that Thermal Foundation would continue to use whatever special process it uses to generate that ore.

**Comment by SvEgiiVEteR** [comment]
Thanks I'll know)
at me simply transferred to the original name.
Now get rid of duplicates ores, ore convenient to original names)

PS
and you know more problematic mod?
eg Railcraft_1.7.10-9.10.0.0.jar
it does not generate the ore in the world if you set the COG ((
need to use RailCraft.xml COG configs
